_target_: mrlfads.datamodules.BasicDataModule

datapath_override: /gscratch/golub/wong2/runs/multi_task/l2_random_runs/multi_task_dms_nogo_h64_l20_l2c1e-3_l2inc200_gseed1629277059_seed1629277059_id2609192321/
filename: ""

session_idxs:
    - 0
    
area_names:
    - A0
    - A1
    - A2
    - A3

batch_size: 16
train_val_split_seed: 42
ignore_info: true