_target_: mrlfads.datamodules.BasicDataModule

datapath_override: /gscratch/golub/wong2/runs/multi_task/l2_random_runs/multi_task_dm_1_h64_l21e-5_l2c1e-2_l2inc200_gseed1060583002_seed1060583002_id2609220054/
filename: ""

session_idxs:
    - 0
    
area_names:
    - A0
    - A1
    - A2
    - A3

batch_size: 16
train_val_split_seed: 42
ignore_info: true