_target_: mrlfads.datamodules.BasicDataModule

datapath_override: /gscratch/golub/wong2/runs/multi_task/l2_random_runs/multi_task_dly_dm_max_h64_l21e-2_l2c1e-3_l2inc200_gseed1932669316_seed1932669316_id2609210633/
filename: ""

session_idxs:
    - 0
    
area_names:
    - A0
    - A1
    - A2
    - A3

batch_size: 16
train_val_split_seed: 42
ignore_info: true