_target_: models.MemoryNetwork

ranks:
  - 1
  - 1
  - 1

connectome:
  - [1, 0, 1]
  - [1, 1, 0]
  - [0, 1, 1]

hidden_size: 64
memory: 2
noise: 0.05
channel_noise: 0.01
lag: 2
input_weight_init_var_scale: 1.5
