_target_: mrlfads.model.MRLFADS

num_other_areas: 3

# ----- Data segmentation ------ #
seq_len: 200
ic_enc_seq_len: 10
hn_indices:
  A0: 
    - [0, 1, 2, 3, 4, 5]
  A1: 
    - [0, 1, 2, 3, 4, 5]
  A2:
    - [0, 1, 2, 3, 4, 5]
  A3:
    - [0, 1, 2, 3, 4, 5]

# --------- learning rate --------- #
lr_init: 5.0e-4
lr_stop: 5.0e-4
lr_decay: 0.999999
lr_patience: 99999
lr_adam_beta1: 0.9
lr_adam_beta2: 0.999
lr_adam_epsilon: 1.0e-8
weight_decay: 0.0

# --------- regularization --------- #
l2_start_epoch: 100
l2_increase_epoch: 80
l2_scale: 1.0e+4
kl_start_epoch_co: 50
kl_increase_epoch_co: 200
kl_start_epoch_com: 150
kl_increase_epoch_com: 100
kl_co_scale: 0.001
kl_com_scale: 0.0001
kl_ic_scale: ${model.kl_co_scale}

# --------- misc --------- #
dropout_rate: 0.3
cell_clip: 5.0
detach_hn: false

# --------- area specification --------- #
areas_params:
    A0:
        # --------- data --------- #
        num_neurons:
          n0: 64
        ext_input_dim: 0
    
        # --------- architecture --------- #
        data_dim: 64
        ic_enc_dim: 64
        ci_enc_dim: 128
        ci_lag: 0
        con_dim: 128
        co_dim: 64
        ic_dim: 64
        gen_dim: 128
        fac_dim: ${model.areas_params.A0.data_dim}
        com_dim: 12
        ci_enc_type: 'bidirectional'

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: mrlfads.utils.torch_utils.ScaledLinear
              in_features: ${model.areas_params.A0.num_neurons.n0}
              out_features: ${model.areas_params.A0.data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: mrlfads.utils.torch_utils.ScaledLinear
              in_features: ${model.areas_params.A0.fac_dim}
              out_features: ${eval:${model.areas_params.A0.num_neurons.n0} * 1}

        # --------- priors / posteriors --------- #
        output_dist:
          _target_: mrlfads.utils.torch_utils.Poisson
        co_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_params.A0.co_dim}
        ic_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_params.A0.ic_dim}
        com_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_params.A0.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        com_post_var_min: 1.0e-4
        
        # --------- regularization --------- #
        kl_ic_scale: ${model.kl_ic_scale}
        kl_co_scale: ${model.kl_co_scale}
        kl_com_scale: ${model.kl_com_scale}
        
    A1:
        # --------- data --------- #
        num_neurons:
          n0: 64
        ext_input_dim: 0
    
        # --------- architecture --------- #
        data_dim: 64
        ic_enc_dim: 64
        ci_enc_dim: 128
        ci_lag: 0
        con_dim: 128
        co_dim: 64
        ic_dim: 64
        gen_dim: 128
        fac_dim: ${model.areas_params.A1.data_dim}
        com_dim: 12
        ci_enc_type: 'bidirectional'

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: mrlfads.utils.torch_utils.ScaledLinear
              in_features: ${model.areas_params.A1.num_neurons.n0}
              out_features: ${model.areas_params.A1.data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: mrlfads.utils.torch_utils.ScaledLinear
              in_features: ${model.areas_params.A1.fac_dim}
              out_features: ${eval:${model.areas_params.A1.num_neurons.n0} * 1}

        # --------- priors / posteriors --------- #
        output_dist:
          _target_: mrlfads.utils.torch_utils.Poisson
        co_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_params.A1.co_dim}
        ic_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_params.A1.ic_dim}
        com_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_params.A1.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        com_post_var_min: 1.0e-4
        
        # --------- regularization --------- #
        kl_ic_scale: ${model.kl_ic_scale}
        kl_co_scale: ${model.kl_co_scale}
        kl_com_scale: ${model.kl_com_scale}
        
    A2:
        # --------- data --------- #
        num_neurons:
          n0: 64
        ext_input_dim: 0
    
        # --------- architecture --------- #
        data_dim: 64
        ic_enc_dim: 64
        ci_enc_dim: 128
        ci_lag: 0
        con_dim: 128
        co_dim: 64
        ic_dim: 64
        gen_dim: 128
        fac_dim: ${model.areas_params.A2.data_dim}
        com_dim: 12
        ci_enc_type: 'bidirectional'

        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: mrlfads.utils.torch_utils.ScaledLinear
              in_features: ${model.areas_params.A2.num_neurons.n0}
              out_features: ${model.areas_params.A2.data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: mrlfads.utils.torch_utils.ScaledLinear
              in_features: ${model.areas_params.A2.fac_dim}
              out_features: ${eval:${model.areas_params.A2.num_neurons.n0} * 1}

        # --------- priors / posteriors --------- #
        output_dist:
          _target_: mrlfads.utils.torch_utils.Poisson
        co_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_params.A2.co_dim}
        ic_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_params.A2.ic_dim}
        com_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_params.A2.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        com_post_var_min: 1.0e-4
        
        # --------- regularization --------- #
        kl_ic_scale: ${model.kl_ic_scale}
        kl_co_scale: ${model.kl_co_scale}
        kl_com_scale: ${model.kl_com_scale}
        
        
    A3:

        # --------- data --------- #
        num_neurons:
          n0: 64
        ext_input_dim: 0
    
        # --------- architecture --------- #
        data_dim: 64
        ic_enc_dim: 64
        ci_enc_dim: 128
        ci_lag: 0
        con_dim: 128
        co_dim: 64
        ic_dim: 64
        gen_dim: 128
        fac_dim: ${model.areas_params.A3.data_dim}
        com_dim: 12
        ci_enc_type: 'bidirectional'
       
        # --------- readin / readout --------- #
        readin:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: mrlfads.utils.torch_utils.ScaledLinear
              in_features: ${model.areas_params.A3.num_neurons.n0}
              out_features: ${model.areas_params.A3.data_dim}
              
        readout:
          _target_: torch.nn.ModuleList
          modules:
            - _target_: mrlfads.utils.torch_utils.ScaledLinear
              in_features: ${model.areas_params.A3.fac_dim}
              out_features: ${eval:${model.areas_params.A3.num_neurons.n0} * 1}

        # --------- priors / posteriors --------- #
        output_dist:
          _target_: mrlfads.utils.torch_utils.Poisson
        co_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_params.A3.co_dim}
        ic_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${model.areas_params.A3.ic_dim}
        com_prior:
          _target_: mrlfads.utils.torch_utils.MultivariateNormal
          mean: 0
          variance: 0.1
          shape: ${eval:${model.areas_params.A3.com_dim} * ${model.num_other_areas}}
        ic_post_var_min: 1.0e-4
        co_post_var_min: 1.0e-4
        com_post_var_min: 1.0e-4
        
        # --------- regularization --------- #
        kl_ic_scale: ${model.kl_ic_scale}
        kl_co_scale: ${model.kl_co_scale}
        kl_com_scale: ${model.kl_com_scale}
        