_target_: models.MultiTaskNet

angle_scale: 1
delay: 5
diagram: null
graph_kwargs:
  perc_conns: 0.67
  shortest: 3
  seed: null

lr_init: 5e-4
l2_scale: 0.0
l2_start: 0
l2_increase: 0
l2_init: 0.0
l2_comm_scale: 0.0
l2_comm_start: 0
l2_comm_increase: 0
l2_comm_init: 0.0
hidden_size: 64

noise: 0.1
noise_start: 0
noise_increase: 200
noise_init: 0.3

num_areas: 4
num_channels: 8
rnn_type: rnncell

sacc_output_areas:
  - '3'
sacc_scale: 0.1

stim_input_areas:
  - A0
  - A1
  - A1
  - A2

task_names: ${datamodule.task_names}