_target_: ttdgn.MultiTaskNet

angle_scale: 1
delay: 5
diagram:
  - - A0
    - A3
    - '0'
  - - A1
    - A0
    - '0'
  - - A1
    - A2
    - '0'
  - - A1
    - A3
    - '0'
  - - A2
    - A1
    - '0'
  - - A3
    - A1
    - '0'
  - - A3
    - A4
    - '1'
    
hidden_size: 64
noise: 0.01
num_areas: 4
num_channels: 8

sacc_output_areas:
  - '3'
sacc_scale: 0.1

stim_input_areas:
  - A0
  - A1
  - A1
  - A2

task_names: ${datamodule.task_names}