on_epoch_end_calls:
  _target_: dgn.callbacks.OnEpochEndCalls
  callbacks:
    - _target_: dgn.callbacks.Log
    - _target_: dgn.callbacks.ProctorSummaryPlot
      log_every_n_epochs: 10
      multiple_acc: True
    - _target_: dgn.ttdgn.TaskRespPlot
      log_every_n_epochs: 10
    - _target_: dgn.callbacks.SaveAsH5
      log_every_n_epochs: 1
      ground_truth:
          - "fix"
          - "stim1"
          - "amp1"
          - "stim2"
          - "amp2"
          - "task"
          - "resp"
          - "sacc"